services:
  - type: web
    name: securelog-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: KAFKA_BOOTSTRAP_SERVERS
        sync: false
      - key: KAFKA_SASL_USERNAME
        sync: false
      - key: KAFKA_SASL_PASSWORD
        sync: false
      - key: KAFKA_LOGS_TOPIC
        value: raw_logs
      - key: KAFKA_ALERTS_TOPIC
        value: alerts
      - key: KAFKA_GROUP_ID
        value: securelog-workers